-- MySQL Script generated by MySQL Workbench
-- 02/23/16 19:38:02
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Cart`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Cart` (
  `ProductID` INT NOT NULL,
  `product` INT NULL,
  `Broiki` INT NULL,
  `PurchasePrice` DECIMAL NULL,
  `CartID` INT NOT NULL,
  `Cartcol` VARCHAR(45) NULL,
  PRIMARY KEY (`CartID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`user` (
  `username` (16) NOT NULL,
  `email` (255) NULL,
  `password` (32) NOT NULL,
  `create_time`  NULL DEFAULT CURRENT_TIMESTAMP,
  `cart` VARCHAR(45) NULL,
  `Cart_CartID` INT NOT NULL,
  PRIMARY KEY (`username`, `Cart_CartID`),
  INDEX `fk_user_Cart1_idx` (`Cart_CartID` ASC),
  CONSTRAINT `fk_user_Cart1`
    FOREIGN KEY (`Cart_CartID`)
    REFERENCES `mydb`.`Cart` (`CartID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Category`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Category` (
  `category_id` INT NOT NULL,
  `name` (255) NOT NULL,
  `SubCatID` INT NULL,
  `SubCatetegory_idSubCatetegory` INT NOT NULL,
  PRIMARY KEY (`category_id`, `SubCatetegory_idSubCatetegory`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`SubCatetegory`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`SubCatetegory` (
  `idSubCatetegory` INT NOT NULL,
  `Category` INT NULL,
  PRIMARY KEY (`idSubCatetegory`),
  INDEX `FK1_idx` (`Category` ASC),
  CONSTRAINT `FK1`
    FOREIGN KEY (`Category`)
    REFERENCES `mydb`.`Category` (`category_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Product`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Product` (
  `idProduct` INT NOT NULL,
  `Category` INT NULL,
  `Productcol` VARCHAR(45) NULL,
  `SubCatID` INT NULL,
  `ProductPrice` DECIMAL NULL,
  `Productcol1` VARCHAR(45) NULL,
  PRIMARY KEY (`idProduct`),
  INDEX `FK1_idx` (`Category` ASC),
  INDEX `FK2_idx` (`SubCatID` ASC),
  CONSTRAINT `FK1`
    FOREIGN KEY (`Category`)
    REFERENCES `mydb`.`Category` (`category_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK2`
    FOREIGN KEY (`SubCatID`)
    REFERENCES `mydb`.`SubCatetegory` (`idSubCatetegory`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`ProductsInCart`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`ProductsInCart` (
  `ProductID` INT NOT NULL,
  `CartID` INT NOT NULL,
  INDEX `FK_Product_idx` (`ProductID` ASC),
  INDEX `FK_Cart_idx` (`CartID` ASC),
  CONSTRAINT `FK_Product`
    FOREIGN KEY (`ProductID`)
    REFERENCES `mydb`.`Product` (`idProduct`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `FK_Cart`
    FOREIGN KEY (`CartID`)
    REFERENCES `mydb`.`Cart` (`CartID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
